export const tags = [
  {
    href: 'wheat-free',
    text: 'Wheat-Free',
  },
  {
    href: 'vegetarian',
    text: 'Vegetarian',
  },
  {
    href: 'vegan',
    text: 'Vegan',
  },
  {
    href: 'tree-nut-free',
    text: 'Tree-Nut-Free',
  },
  {
    href: 'sulfite-free',
    text: 'Sulfite-Free',
  },
  {
    href: 'sugar-conscious',
    text: 'Sugar-Conscious',
  },
  {
    href: 'soy-free',
    text: 'Soy-Free',
  },
  {
    href: 'shellfish-free',
    text: 'Shellfish-Free',
  },
  {
    href: 'sesame-free',
    text: 'Sesame-Free',
  },
  {
    href: 'red-meat-free',
    text: 'Red-Meat-Free',
  },
  {
    href: 'pork-free',
    text: 'Pork-Free',
  },
  {
    href: 'pecatarian',
    text: 'Pescatarian',
  },
  {
    href: 'peanut-free',
    text: 'Peanut-Free',
  },
  {
    href: 'paleo',
    text: 'Paleo',
  },
  {
    href: 'No-oil-added',
    text: 'No-oil-added',
  },
  {
    href: 'mustard-free',
    text: 'Mustard-Free',
  },
  {
    href: 'mollusk-free',
    text: 'Mollusk-Free',
  },
  {
    href: 'Mediterranean',
    text: 'Mediterranean',
  },
  {
    href: 'lupine-free',
    text: 'Lupine-Free',
  },
  {
    href: 'low-sugar',
    text: 'Low Sugar',
  },
  {
    href: 'low-potassium',
    text: 'Low Potassium',
  },
  {
    href: 'kosher',
    text: 'Kosher',
  },
  {
    href: 'kidney-friendly',
    text: 'Kidney-Friendly',
  },
  {
    href: 'keto-friendly',
    text: 'Keto-Friendly',
  },
  {
    href: 'immuno-supportive',
    text: 'Immuno-Supportive',
  },
  {
    href: 'gluten-free',
    text: 'Gluten-Free',
  },
  {
    href: 'fodmap-free',
    text: 'FODMAP-Free',
  },
  {
    href: 'fish-free',
    text: 'Fish-Free',
  },
  {
    href: 'egg-free',
    text: 'Egg-Free',
  },
  {
    href: 'DASH',
    text: 'DASH',
  },
  {
    href: 'dairy-free',
    text: 'Dairy-Free',
  },
  {
    href: 'crustacean-free',
    text: 'Crustcean-Free',
  },
  {
    href: 'celery-free',
    text: 'Celery-Free',
  },
  {
    href: 'alcohol-free',
    text: 'Alcohol-Free',
  },
  {
    href: 'alcohol-cocktail',
    text: 'Alcohol-Cocktail',
  },
];
export const accordionItem = [
  {
    container: 'cook-time',
    icon: 'timer',
    title: 'Cooking Time',
    filter: 'time',

    data: [
      { label: '< 5 minutes', value: '5', name: 'cook-time', type: 'radio' },
      { label: '5-10 minutes', value: '5-10', name: 'cook-time', type: 'radio' },
      { label: '10-20 minutes', value: '10-20', name: 'cook-time', type: 'radio' },
      { label: '20-30 minutes', value: '20-30', name: 'cook-time', type: 'radio' },
      { label: '30-40 minutes', value: '30-40', name: 'cook-time', type: 'radio' },
      { label: '40-50 minutes', value: '40-50', name: 'cook-time', type: 'radio' },
      { label: '50-60 minutes', value: '50-60', name: 'cook-time', type: 'radio' },
      { label: '< 1 hour', value: '60+', name: 'cook-time', type: 'radio' },
    ],
  },
  {
    container: 'ingr',
    icon: 'nutrition',
    title: 'Ingredients',
    filter: 'ingr',
    data: [
      { label: '< 5 Ingredients', value: '5', name: 'ingr', type: 'radio' },
      { label: '5-10 Ingredients', value: '5-10', name: 'ingr', type: 'radio' },
      { label: '10-20 Ingredients', value: '10-20', name: 'ingr', type: 'radio' },
      { label: '20-30 Ingredients', value: '20-30', name: 'ingr', type: 'radio' },
      { label: '> 30 Ingredients', value: '30+', name: 'ingr', type: 'radio' },
    ],
  },
  {
    container: 'calories',
    icon: 'ulna_radius_alt',
    title: 'Calories',
    filter: 'calories',
    data: [
      { label: '50', value: '50', name: 'calories', type: 'radio' },
      { label: '50-100', value: '50-100', name: 'calories', type: 'radio' },
      { label: '100-200', value: '100-200', name: 'calories', type: 'radio' },
      { label: '200-300', value: '200-300', name: 'calories', type: 'radio' },
      { label: '300-400', value: '300-400', name: 'calories', type: 'radio' },
      { label: '400-500', value: '400-500', name: 'calories', type: 'radio' },
      { label: '> 500', value: '500+', name: 'calories', type: 'radio' },
    ],
  },
  {
    container: 'diet',
    icon: 'spa',
    title: 'Diet',
    filter: 'diet',
    data: [
      { label: 'balanced', value: 'balanced', name: 'balanced', type: 'checkbox' },
      {
        label: 'high fiber',
        value: 'high-fiber',
        name: 'high fiber',
        type: 'checkbox',
      },
      {
        label: 'high protien',
        value: 'high-protien',
        name: 'high protien',
        type: 'checkbox',
      },
      { label: 'low carb', value: 'low-carb', name: 'low carb', type: 'checkbox' },
      { label: 'low fat', value: 'low-carb', name: 'low fat', type: 'checkbox' },
      {
        label: 'low sodium',
        value: 'low-sodium',
        name: 'low sodium',
        type: 'checkbox',
      },
      {
        label: 'low sodium',
        value: 'low-sodium',
        name: 'low sodium',
        type: 'checkbox',
      },
    ],
  },
  {
    container: 'health',
    icon: 'health_and_safety',
    title: 'Health',
    filter: 'health',
    data: [
      {
        label: 'Alcohol Cocktail',
        value: 'Alcohol-Cocktail',
        name: 'Alcohol Cocktail',
        type: 'checkbox',
      },
      {
        label: 'Alcohol Free',
        value: 'Alcohol-Free',
        name: 'Alcohol Free',
        type: 'checkbox',
      },
      {
        label: 'Celery Free',
        value: 'Celery-Free',
        name: 'Celery Free',
        type: 'checkbox',
      },
      {
        label: 'Crustcean Free',
        value: 'Crustcean-Free',
        name: 'Crustcean Free',
        type: 'checkbox',
      },
      {
        label: 'Dairy Free',
        value: 'Dairy-Free',
        name: 'Dairy Free',
        type: 'checkbox',
      },
      {
        label: 'DASH',
        value: 'DASH',
        name: 'DASH',
        type: 'checkbox',
      },
      {
        label: 'Egg Free',
        value: 'Egg-Free',
        name: 'Egg Free',
        type: 'checkbox',
      },
      {
        label: 'Fish Free',
        value: 'Fish-Free',
        name: 'Fish Free',
        type: 'checkbox',
      },
      {
        label: 'FODMAP Free',
        value: 'FODMAP-Free',
        name: 'FODMAP Free',
        type: 'checkbox',
      },
      {
        label: 'Gluten Free',
        value: 'Gluten-Free',
        name: 'Gluten Free',
        type: 'checkbox',
      },
      {
        label: 'Keto Friendly',
        value: 'Immuno-Supportive',
        name: 'Immuno Supportive',
        type: 'checkbox',
      },
      {
        label: 'Keto Friendly',
        value: 'Keto-Friendly',
        name: 'Keto Friendly',
        type: 'checkbox',
      },
      {
        label: 'Kidney Friendly',
        value: 'Kidney-Friendly',
        name: 'Kidney Friendly',
        type: 'checkbox',
      },
      {
        label: 'Kosher',
        value: 'Kosher',
        name: 'Kosher',
        type: 'checkbox',
      },
      {
        label: 'Low Fat Abs',
        value: 'Low-Fat-Abs',
        name: 'Low Fat Abs',
        type: 'checkbox',
      },
      {
        label: 'Low Potassium',
        value: 'Low-Potassium',
        name: 'Low Potassium',
        type: 'checkbox',
      },
      {
        label: 'Low Sugar',
        value: 'Low-Sugar',
        name: 'Low Sugar',
        type: 'checkbox',
      },
      {
        label: 'Lupine Free',
        value: 'Lupine-Free',
        name: 'Lupine Free',
        type: 'checkbox',
      },
      {
        label: 'Mediterranean',
        value: 'Mediterranean',
        name: 'Mediterranean',
        type: 'checkbox',
      },
      {
        label: 'Mediterranean',
        value: 'Mediterranean',
        name: 'Mediterranean',
        type: 'checkbox',
      },
      {
        label: 'Mollusk Free',
        value: 'Mollusk-Free',
        name: 'Mollusk Free',
        type: 'checkbox',
      },
      {
        label: 'Mustard Free',
        value: 'Mustard-Free',
        name: 'Mustard Free',
        type: 'checkbox',
      },
      {
        label: 'No oil added',
        value: 'No-oil-added',
        name: 'No oil added',
        type: 'checkbox',
      },
      {
        label: 'Paleo',
        value: 'Paleo',
        name: 'Paleo',
        type: 'checkbox',
      },
      {
        label: 'Peanut Free',
        value: 'Peanut-Free',
        name: 'Peanut Free',
        type: 'checkbox',
      },
      {
        label: 'Paleo',
        value: 'Paleo',
        name: 'Paleo',
        type: 'checkbox',
      },
      {
        label: 'Pescatarian',
        value: 'Pescatarian',
        name: 'Pescatarian',
        type: 'checkbox',
      },
      {
        label: 'Pork Free',
        value: 'Pork-Free',
        name: 'Pork Free',
        type: 'checkbox',
      },
      {
        label: 'Red Meat Free',
        value: 'Red-Meat-Free',
        name: 'Red Meat Free',
        type: 'checkbox',
      },
      {
        label: 'Pescatarian',
        value: 'Pescatarian',
        name: 'Pescatarian',
        type: 'checkbox',
      },
      {
        label: 'Sesame Free',
        value: 'Sesame-Free',
        name: 'Sesame Free',
        type: 'checkbox',
      },
      {
        label: 'Shellfish Free',
        value: 'Shellfish-Free',
        name: 'Shellfish Free',
        type: 'checkbox',
      },
      {
        label: 'Soy Free',
        value: 'Soy-Free',
        name: 'Soy Free',
        type: 'checkbox',
      },
      {
        label: 'Sugar Conscious',
        value: 'Sugar-Conscious',
        name: 'Sugar Conscious',
        type: 'checkbox',
      },
      {
        label: 'Sulfite Free',
        value: 'Sulfite-Free',
        name: 'Sulfite Free',
        type: 'checkbox',
      },
      {
        label: 'Tree Nut Free',
        value: 'Tree-Nut-Free',
        name: 'Tree Nut Free',
        type: 'checkbox',
      },
      {
        label: 'Vegan',
        value: 'Vegan',
        name: 'Vegan',
        type: 'checkbox',
      },
      {
        label: 'Vegetarian',
        value: 'Vegetarian',
        name: 'Vegetarian',
        type: 'checkbox',
      },
      {
        label: 'Wheat Free',
        value: 'Wheat-Free',
        name: 'Wheat Free',
        type: 'checkbox',
      },
      {
        label: 'Pescatarian',
        value: 'Pescatarian',
        name: 'Pescatarian',
        type: 'checkbox',
      },
      {
        label: 'Pescatarian',
        value: 'Pescatarian',
        name: 'Pescatarian',
        type: 'checkbox',
      },
    ],
  },
  {
    container: 'meal',
    icon: 'restaurant',
    title: 'Meal',
    filter: 'mealType',
    data: [
      {
        label: 'Breakfast',
        value: 'Breakfast',
        name: 'Breakfast',
        type: 'checkbox',
      },
      {
        label: 'Dinner',
        value: 'Dinner',
        name: 'Dinner',
        type: 'checkbox',
      },
      {
        label: 'Lunch',
        value: 'Lunch',
        name: 'Lunch',
        type: 'checkbox',
      },
      {
        label: 'Snack',
        value: 'Snack',
        name: 'Snack',
        type: 'checkbox',
      },
      {
        label: 'Teatime',
        value: 'Teatime',
        name: 'Teatime',
        type: 'checkbox',
      },
    ],
  },
  {
    container: 'dish',
    icon: 'fastfood',
    title: 'Dish',
    filter: 'dishType',
    data: [
      {
        label: 'Biscuits and cookies',
        value: 'Biscuits-and-cookies',
        name: 'Biscuits and cookies',
        type: 'checkbox',
      },
      {
        label: 'Bread',
        value: 'Bread',
        name: 'Bread',
        type: 'checkbox',
      },
      {
        label: 'Cereals',
        value: 'Cereals',
        name: 'Cereals',
        type: 'checkbox',
      },
      {
        label: 'Condiments and sauces',
        value: 'Condiments-and-sauces',
        name: 'Condiments and sauces',
        type: 'checkbox',
      },
      {
        label: 'Desserts',
        value: 'Desserts',
        name: 'Desserts',
        type: 'checkbox',
      },
      {
        label: 'Drinks',
        value: 'Drinks',
        name: 'Drinks',
        type: 'checkbox',
      },
      {
        label: 'Main course',
        value: 'Main-course',
        name: 'Main course',
        type: 'checkbox',
      },
      {
        label: 'Teatime',
        value: 'Teatime',
        name: 'Teatime',
        type: 'checkbox',
      },
      {
        label: 'Pancake',
        value: 'Pancake',
        name: 'Pancake',
        type: 'checkbox',
      },
      {
        label: 'Preps',
        value: 'Preps',
        name: 'Preps',
        type: 'checkbox',
      },
      {
        label: 'Preserve',
        value: 'Preserve',
        name: 'Preserve',
        type: 'checkbox',
      },
      {
        label: 'Salad',
        value: 'Salad',
        name: 'Salad',
        type: 'checkbox',
      },
      {
        label: 'Sandwiches',
        value: 'Sandwiches',
        name: 'Sandwiches',
        type: 'checkbox',
      },
      {
        label: 'Side dish',
        value: 'Side-dish',
        name: 'Side dish',
        type: 'checkbox',
      },
      {
        label: 'Soup',
        value: 'Soup',
        name: 'Soup',
        type: 'checkbox',
      },
      {
        label: 'Starter',
        value: 'Starter',
        name: 'Starter',
        type: 'checkbox',
      },
      {
        label: 'Sweets',
        value: 'Sweets',
        name: 'Sweets',
        type: 'checkbox',
      },
    ],
  },
  {
    container: 'cuisine',
    icon: 'public',
    title: 'Cuisine',
    filter: 'cuisineType',
    data: [
      {
        label: 'American',
        value: 'American',
        name: 'American',
        type: 'checkbox',
      },
      {
        label: 'Asian',
        value: 'Asian',
        name: 'Asian',
        type: 'checkbox',
      },
      {
        label: 'British',
        value: 'British',
        name: 'British',
        type: 'checkbox',
      },
      {
        label: 'Caribbean',
        value: 'Caribbean',
        name: 'Caribbean',
        type: 'checkbox',
      },
      {
        label: 'Central Europe',
        value: 'Central-Europe',
        name: 'Central Europe',
        type: 'checkbox',
      },
      {
        label: 'Chinese',
        value: 'Chinese',
        name: 'Chinese',
        type: 'checkbox',
      },
      {
        label: 'Eastern Europe',
        value: 'Eastern-Europe',
        name: 'Eastern Europe',
        type: 'checkbox',
      },
      {
        label: 'French',
        value: 'French',
        name: 'French',
        type: 'checkbox',
      },
      {
        label: 'Indian',
        value: 'Indian',
        name: 'Indian',
        type: 'checkbox',
      },
      {
        label: 'Italian',
        value: 'Italian',
        name: 'Italian',
        type: 'checkbox',
      },
      {
        label: 'Japanese',
        value: 'Japanese',
        name: 'Japanese',
        type: 'checkbox',
      },
      {
        label: 'Kosher',
        value: 'Kosher',
        name: 'Kosher',
        type: 'checkbox',
      },
      {
        label: 'Kosher',
        value: 'Kosher',
        name: 'Kosher',
        type: 'checkbox',
      },
      {
        label: 'Mediterranean',
        value: 'Mediterranean',
        name: 'Mediterranean',
        type: 'checkbox',
      },
      {
        label: 'Mexican',
        value: 'Mexican',
        name: 'Mexican',
        type: 'checkbox',
      },
      {
        label: 'Middle Eastern',
        value: 'Middle-Eastern',
        name: 'Middle Eastern',
        type: 'checkbox',
      },
      {
        label: 'Nordic',
        value: 'Nordic',
        name: 'Nordic',
        type: 'checkbox',
      },
      {
        label: 'South American',
        value: 'South-American',
        name: 'South American',
        type: 'checkbox',
      },
      {
        label: 'East Asian',
        value: 'East-Asian',
        name: 'East Asian',
        type: 'checkbox',
      },
    ],
  },
];
